# -*- coding: utf-8 -*-
"""ecomerce sales analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/naima558/9fdbfa03426b5bb35c071393ffb8d636/copy-of-untitled0.ipynb
"""

import pandas as pd

df = pd.read_csv("ecommerce_sales (1).csv")

df.info()
df.describe()
df.head()
df.tail()

bu kısımda explarotary data analysis yapıyoruz veri setimizi keşfediyoruz

df["Product"].value_counts().head(10)  # hangi urun kaç kez satıldığını gosterir
df["Country"].value_counts().head(10)  # ulkere gore siparış sayısını gosterir
df["Total"] = df["Quantity"] * df["UnitPrice"] # her siparişin toplam tutarini hesaplar
df[["Product", "Quantity", "UnitPrice", "Total"]].head()
df["Total"].sum() # tum siparişlerin toplam değeri
df["Total"].mean() # her siparişin ortalama tutarını hesaplar

df.groupby("Country")["Total"].sum().sort_values(ascending=False).head(10) #ülkelere göre toplam gelir
df.groupby("Product")["Total"].sum().sort_values(ascending=False).head(10) # en çok gelir getiren ürünler
df.groupby("Category")["Total"].mean().sort_values(ascending=False) # her katagori için ortalama şipariş geliri
df["Date"] = pd.to_datetime(df["Date"])  # tarih sütünü tarih formatına çevire
df.groupby(df["Date"].dt.to_period("M"))["Total"].sum()

>

import matplotlib.pyplot as plt
import seaborn as sns

# en çok satılan urunler
top_products = df["Product"].value_counts().head(10)

plt.figure(figsize=(10,6))
sns.barplot(x=top_products.values, y=top_products.index)
plt.title("En Çok Satılan 10 Ürün")
plt.xlabel("Satış Sayısı")
plt.ylabel("Ürün Adı")
plt.tight_layout()
plt.show()

# ulkelere gore toplam gelir
country_sales = df.groupby("Country")["Total"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,8))
plt.pie(country_sales.values, labels=country_sales.index, autopct="%1.1f%%", startangle=140)
plt.title("Ülkelere Göre Toplam Gelir (En Yüksek 10 Ülke)")
plt.axis("equal")  # Daireyi düzgün gösterir
plt.show()

# aylara göre guruplandırma
monthly_sales = df.groupby(df["Date"].dt.to_period("M"))["Total"].sum()

plt.figure(figsize=(12,6))
monthly_sales.plot(kind="line", marker="o")
plt.title("Aylık Satış Trendi")
plt.xlabel("Ay")
plt.ylabel("Toplam Gelir")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# katagorileri göre ortalama sipariş geliri
category_avg = df.groupby("Category")["Total"].mean().sort_values(ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(x=category_avg.values, y=category_avg.index)
plt.title("Kategorilere Göre Ortalama Sipariş Geliri")
plt.xlabel("Ortalama Gelir")
plt.ylabel("Kategori")
plt.tight_layout()
plt.show()